var context = {
	timers: [],
	intervals: [],
	isMuted: false,
	pause: {rect: null, isPaused: false, play: 0},
	b1Svg: "mod5/5b1.xml",
	b1Mp3: "mod5/Audio/5b1.mp3",
	b1Ogg: "mod5/Audio/5b1.ogg",
	b2Svg: "mod5/5b2.xml",
	b2Mp3: "mod5/Audio/5b2.mp3",
	b2Ogg: "mod5/Audio/5b2.ogg",
	b3Mp3: "mod5/Audio/5b3.mp3",
	b3Ogg: "mod5/Audio/5b3.ogg",
	b3Instructions: {text: "Now it's your turn.\nUse your mouse to\nclick and hold the\nchild's mouth to\ndeliver two breaths. ", x: 400, y: 100},
	b3Fail: "Sorry you did not give two breaths.\nRemember to hold the breath for\nabout one second, until you see the\nchest rise.  Would you like to\ntry again or continue on?",
	b3Success: "That's right. Would you\nlike to try again\nor continue on?",
	b3FailMp3:  "mod5/Audio/5b3Fail.mp3",
	b3FailOgg:  "mod5/Audio/5b3Fail.ogg",
	b3Complete: "fiveLoc.html",
	b3SuccessMp3:  "mod5/Audio/5b3Success.mp3",
	b3SuccessMp3:  "mod5/Audio/5b3Success.ogg",
	headTranslate: {x: 10, y: 37, t: 500},
	scale: {kx: 1.25, ky: 1.25, x: 380, y: 300}, 
};
