var context = {
	timers: [],
	intervals: [],
	isMuted: false,
	pause: {rect: null, isPaused: false, play: 0},
	b1Svg: "mod4/4b1.xml",
	b1Mp3: "mod4/Audio/4b1.mp3",
	b1Ogg: "mod4/Audio/4b1.ogg",
	b2Svg: "mod4/4b2.xml",
	b2Mp3: "mod4/Audio/4b2.mp3",
	b2Ogg: "mod4/Audio/4b2.ogg",
	b3Mp3: "mod4/Audio/4b3.mp3",
	b3Ogg: "mod4/Audio/4b3.ogg",
	b3Instructions: {text: "Now it's your turn.\nUse your mouse to\nclick and hold the\nchild's mouth to\ndeliver two breaths. ", x: 420, y: 100},
	b3Fail: "Sorry you did not give two breaths.\nRemember to hold the breath for\nabout one second, until you see the\nchest rise.  Would you like to\ntry again or continue on?",
	b3Success: "That's right. Would you\nlike to try again\nor continue on?",
	b3FailMp3:  "mod4/Audio/4b3Fail.mp3",
	b3FailOgg:  "mod4/Audio/4b3Fail.ogg",
	b3Complete: "fourLoc.html",
	b3SuccessMp3:  "mod4/Audio/4b3Success.mp3",
	b3SuccessOgg:  "mod4/Audio/4b3Success.ogg",
	headTranslate: {x: 10, y: 32, t: 500},
	scale: {kx: 1.3, ky: 1.3, x: 380, y: 380}, 
};
