var context = {
	timers: [],
	intervals: [],
	isMuted: false,
	pause: {rect: null, isPaused: false, play: 0},
	b1Svg: "mod3/3b1.xml",
	b1Mp3: "mod3/Audio/3b1.mp3",
	b1Ogg: "mod3/Audio/3b1.ogg",
	b2Svg: "mod3/3b2.xml",
	b2Mp3: "mod3/Audio/3b2.mp3",
	b2Ogg: "mod3/Audio/3b2.ogg",
	b3Mp3: "mod3/Audio/3b3.mp3",
	b3Ogg: "mod3/Audio/3b3.ogg",
	b3Instructions: {text: "Now it's your turn.  Use\nyour mouse to click and\nhold the infant's mouth\nto deliver two breaths.", x: 350, y: 100},
	b3Fail: "Sorry you did not give two breaths.\nRemember to hold the breath for\nabout one second, until you see the\nchest rise.  Would you like to\ntry again or continue on?",
	b3Success: "That's right. Would you\nlike to try again\nor continue on?",
	b3Complete: "threeLoc.html",
	b3FailMp3:  "mod3/Audio/3b3Fail.mp3",
	b3FailOgg:  "mod3/Audio/3b3Fail.ogg",
	b3SuccessMp3:  "mod3/Audio/3b3Success.mp3",
	b3SuccessOgg:  "mod3/Audio/3b3Success.ogg",
	headTranslate: {x: 10, y: 40, t: 500},
	scale: {kx: 1.6, ky: 1.6, x: 340, y: 380}, 
};
